nryoung/algorithms

algorithms/data_structure/queue.py
algorithms/data_structure/stack.py
algorithms/tests/test_data_structure.py
setup.py

Data Structure Implemented

---

README.rst
algorithms/sorting/gnome_sort.py
algorithms/tests/test_sorting.py

Added an optimised version of Gnome sort (as per the wikipedia page pseudo code) and a unit test for it.

Gnome Sort

---

algorithms/data_structure/union_find.py
algorithms/data_structure/union_find_by_rank.py
algorithms/data_structure/union_find_with_path_compression.py
algorithms/tests/test_data_structure.py

Thanks for creating this project. This is my first pull request. Next, I am going to implement two Union Find improvements according to http://en.wikipedia.org/wiki/Disjoint-set_data_structure.

Adding Union Find - Navie approach

---

algorithms/math/primality_test.py
algorithms/math/sieve_eratosthenes.py

The problem with the present implementation is that we are deleting a log of items from the list which makes this very inefficient. 
The example implementation I provided will return primes upto 1 million in less than half second while the present implementation takes more than 1 second for primes upto 1000

make sieve of eratosthenes efficient

---

algorithms/data_structure/singly_linked_list.py
algorithms/tests/test_data_structure.py

Added Singly Linked List Data Structure and the corresponding Unit Test

Added Singly Linked List Data Structure and the corresponding Unit Test

---

algorithms/data_structure/undirected_graph.py
algorithms/tests/test_data_structure.py

This PR includes an implementation for an Undirected Graph Data structure as inspired by http://algs4.cs.princeton.edu/41undirected/Graph.java.html.

Adding Undirected Graph

---

algorithms/data_structure/digraph.py
algorithms/tests/test_data_structure.py

This PR adds an implementation for a Directed Graph as adapted from http://algs4.cs.princeton.edu/42directed/Digraph.java.html.

Adding digraph

---

algorithms/data_structure/binary_search_tree.py
algorithms/tests/test_data_structure.py

This PR adds a BST implementation with tests.  Commits have been rebased and squashed as desired.

Adding BST implementation

---

README.rst
TODO.rst
algorithms/dynamic_programming/lcs.py
algorithms/tests/test_dynamic_programming.py
setup.py

Add dynamic_programming package to setup.py

Add Longest Common Subsequence algorithm

---

README.rst
algorithms/tests/test_math.py
requirements.txt
run_tests.py

- Update requirements
- Update README
- Add run_tests module to run tests
- Change math tests to use builtin assertAlmostEqual

Change to pytest as the test runner, fixes #100

---

run_tests.py
tests/test_data_structure.py
tests/test_dynamic_programming.py
tests/test_math.py
tests/test_random.py
tests/test_searching.py
tests/test_shuffling.py
tests/test_sorting.py

- Remove all relative imports from the tests

Move tests up one directory level, fixes #107

---

.travis.yml
requirements.txt
setup.py
tox.ini

- Change tox over to the script run by Travis CI

Add tox, fixes #96

---

algorithms/factorization/fermat.py
algorithms/factorization/pollard_rho.py
algorithms/factorization/trial_division.py
tests/test_factorization.py

this PR include 3 factorization algorithms : the simple trial divide, pollard rho and fermat

include some factorization algorithms

---

AUTHORS.rst
README.rst
TODO.rst
algorithms/sorting/strand_sort.py
tests/test_sorting.py

Spent the past couple days working on this, with help from [gengisteve](https://reddit.com/u/gengisteve).

Added Strand sort.

---

algorithms/sorting/strand_sort.py

Also now handles already sorted lists in O(1) time.

Improved Strand Sort speed dramatically.

---

.gitignore
README.rst
algorithms/searching/breadth_first_search.py
tests/test_searching.py

<h1>Breadth First Search (BFS)</h1>
<h3>A Searching Algorithm Based on Graph Traversal</h3>
<h6>Breadth First Search Vs. Depth First Search</h6>
<li> `BFS` uses a **queue** (FIFO) data structure in its implementation.
<li> `DFS` uses a **stack** (FILO) data structure in its implementation. </li>
1. I added the **implementation** of the breadth first search algorithm.
2. I added the **proper tests** for the breadth first search algorithm.
Please let me know if there is anything else that I need to add :smile:.

Breadth First Search (BFS)

---

README.rst
docs/index.rst

Add docs link to README

---

README.rst

Add docs badge to README

---

docs/data_structures.rst

I forgot to add this file for tracking.

Add data structure docs to repo.

---

README.rst
setup.py

- Add pypi version badge, fixes #128

Update version to 1.0, McLovin is finally here.

---

.travis.yml
algorithms/data_structures/lcp_array.py
docs/sorting.rst
tests/test_data_structures.py

The implementation is correct, but some optimizations should be done (ex: we can replace suffix array by suffix trees to reduce complexity to O(n)),  I will do it in next commits.

Add Suffix and LCP arrays algorithms

---

algorithms/data_structures/stack.py

* `Size()` method is already present to calculate length of stack ,reusing this method to check stack empty or not  .
* Removed class variable declaration which isn't required
@nryoung Please review this PR

Using Size() method to check if stack is empty , removed unnecessary class variable declaration 

---

algorithms/sorting/bubble_sort.py

the range for n should be 1 to length-i.
No need to compare from first to last every time.

fix the logic about bubble sort.

---

algorithms/dynamic_programming/lcs.py

Fixing typo on LCS

---

algorithms/data_structures/undirected_graph.py

This fixes the spelling error in the documentation here:
http://algorithms.readthedocs.io/en/latest/data_structures.html#unidrected-graph

Correct spelling error in documentation

---

.gitignore
algorithms/data_structures/queue.py
tests/test_factorization.py

Remove unnecessary queue_list variable in Queue class, and ignore .cache/ directory after tests

Remove unnecessary Queue class variable

---

algorithms/dynamic_programming/lcs.py

Ics.py comment header typo

---

algorithms/data_structures/singly_linked_list.py

fix error for removing not existing node in single linked list
